default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :match_test do
    match(
        type: "appstore",
        readonly: true,
        app_identifier: BUNDLE_ID
    )
  end
end
